// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bggxsuuphihqjqcbzcrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ3hzdXVwaGlocWpxY2J6Y3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNDAyNTQsImV4cCI6MjA4OTYxNjI1NH0.o8_URovtv3UFrkpQF0IDdAERgnUNJCeRH2X3JOg9RQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});